# Generated by Django 5.0.6 on 2025-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('cash_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('vnpay_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('bank_transfer_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('cash_orders', models.IntegerField(default=0)),
                ('vnpay_orders', models.IntegerField(default=0)),
                ('bank_transfer_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revenue Statistics',
                'verbose_name_plural': 'Revenue Statistics',
                'db_table': 'revenue_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='revenue_sta_date_4a466e_idx'), models.Index(fields=['created_at'], name='revenue_sta_created_78ffd5_idx')],
            },
        ),
    ]
