# Generated by Django 4.2.7 on 2025-10-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_enhance_payment_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_vnp_txn_1624ee_idx',
            old_name='payments_vnp_txn_ref_idx',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
    ]
